modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="electronics"
version="0.0.1"
displayName="ElectronicsMod"
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="electronics.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
This a description !
'''
[[dependencies.electronics]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.electronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"